# Generated by Django 3.2.12 on 2022-08-09 12:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_secret_sharing", "0002_auto_20220525_1008"),
    ]

    operations = [
        migrations.AddField(
            model_name="secret",
            name="expires_in",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("expires_in", models.IntegerField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ref", models.TextField()),
                (
                    "secret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="django_secret_sharing.secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "abstract": False,
            },
        ),
    ]
