# Generated by Django 5.2.17 on 2026-09-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_secret_sharing", "0003_auto_20220809_1207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="ref",
            field=models.TextField(unique=True),
        ),
    ]
